# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pJ63gr-cFx2zz4pRdVIz-T2wkv1FNOB
"""


import googlemaps
from kafka import KafkaProducer
import json
from datetime import datetime
import time

# API Key
google_maps_api_key = "AIzaSyDNmKMQUCvsiJCdT_344PJ4MHMM_CiGE8c"

# Initialize Google Maps client
gmaps = googlemaps.Client(key=google_maps_api_key)

# Kafka broker address
kafka_broker = "localhost:9092"

# Initialize Kafka producer with proper serializer
producer = KafkaProducer(
    bootstrap_servers=kafka_broker,
    value_serializer=lambda v: json.dumps(v).encode('utf-8')
)

# Kafka topic to send data to
kafka_topic = "google-maps-traffic-data"

# Example: Get traffic data using Google Maps Directions API
origin = "New York, NY, USA"
destination = "Boston, MA, USA"

# Get traffic data with current time
directions = gmaps.directions(
    origin,
    destination,
    mode="driving",
    departure_time="now"
)

# Extract ETA from the directions data
if directions:
    route = directions[0]
    leg = route["legs"][0]
    eta_in_seconds = leg["duration_in_traffic"]["value"]
    eta_formatted = leg["duration_in_traffic"]["text"]

    # Prepare the data to send to Kafka
    data = {
        "origin": origin,
        "destination": destination,
        "eta_in_seconds": eta_in_seconds,
        "eta_formatted": eta_formatted,
        "timestamp": str(datetime.now())
    }

    # Send the data to Kafka
    producer.send(kafka_topic, data)

# Ensure the data is sent
producer.flush()
